repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
        exclude_types: [jupyter]
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: check-illegal-windows-names
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: fix-byte-order-marker
    -   id: forbid-submodules
    -   id: mixed-line-ending
      # - id: name-tests-test # we should obey this
    -   id: requirements-txt-fixer
    -   id: check-added-large-files

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    -   id: black-jupyter

-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-simplify

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update
